install.packages("dplyr")
install.packages("tidyverse")
install.packages("data.table")
install.packages("DT")
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("ensembldb")
BiocManager::install("EnsDb.Hsapiens.v75")
install.packages("locuszoomr")
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("biomaRt")

library(dplyr)
library(tidyverse) 
library(data.table)
library(DT)
library(ensembldb)
library(EnsDb.Hsapiens.v75)
library(locuszoomr)
library(biomaRt)
