install.packages("dplyr")
install.packages("tidyverse")
install.packages("data.table")
install.packages("DT")
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("ensembldb")
BiocManager::install("EnsDb.Hsapiens.v75")
install.packages("locuszoomr")
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("biomaRt")
install.packages("remotes")
remotes::install_version('RcppEigen', version = '0.3.3.9.3')
remotes::install_github('jrs95/hyprcoloc', build_opts = c('--no-resave-data', '--no-manual'), upgrade = 'never', build_vignettes = TRUE)

library(dplyr)
library(tidyverse) 
library(data.table)
library(DT)
library(ensembldb)
library(EnsDb.Hsapiens.v75)
library(locuszoomr)
library(biomaRt)
library(hyprcoloc)